version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=AbcMoneyTransfer;User=sa;Password=Secret@1!;Trusted_Connection=False;Encrypt=false;MultipleActiveResultSets=true;
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Secret@1!
      - ACCEPT_EULA=Y
    ports:
      - "1437:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
